#this is a section for models
models:
  - name: model1
    columns:
     - a
  - name: model2
    columns:
     - conflictedColumn1
  - name: model3
    columns:
     - c
  - name: model4
    columns:
     - d
