#this is a section for models
models:
  - name: model1
    columns:
     - a
  - name: model2
    columns:
     - conflictedColumn2
  - name: model3
    columns:
     - c
       - d
  - name: model4
    columns:
     - updatedColumn
